site_name: hello world
site_url: https://duilec.github.io/mkdocs-test/
site_author: duilec

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant #- header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮

  language: zh # 一些提示性的文字会变成中文

  icon:
    repo: fontawesome/brands/github #右上角图标

# edit_uri: edit/main/docs # 编辑按钮跳转的链接，右上角，但是在文章内部的右上角
repo_url: https://duilec.github.io/mkdocs-test/ # 右上角点击跳转的链接
repo_name: duilec.github.io/mkdocs-test # 右上角的名字

nav:
  - Home: index.md
  - Getting started:
    - a: getting_started/index.md
  - Others:
    - a: others/index.md

copyright: Copyright &copy; duilec # 左下角的版权声明

# 右下角的社交联系方式
extra:
  generator: true  #删除页脚显示“使用 MkDocs 材料制造”
  #联系方式图标 : https://fontawesome.com/ 去这里找图标
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/duilec
    - icon: fontawesome/solid/envelope
      link: mailto:<elelsyqrlc42@163.com> #联系方式

# markdown相关配置
markdown_extensions:   #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

plugins:
  - search   #搜索配置
  # - git-revision-date-localized:
  #     type: iso_date
  #     enable_creation_date: false
  #     exclude:
  #       - index.md 
  #       - tag.md
  #       - liuyanban.md
  #       - blog/posts/update.md
  #       - blog/posts/wkw.md
  #       - about/link.md 
  # - blog:   #博客配置
  #     post_date_format: full #时间
  #     draft: true
  #     draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
  #     post_readtime: true
  #     post_readtime_words_per_minute: 265  #计算帖子的阅读时间时读者每分钟预计阅读的字数
  #     post_url_format: "{date}/{slug}"
  #     # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
  #     #   kwds:
  #     #     case: lower
  #     pagination_url_format: "page/{page}"
  #     authors_file: "{blog}/.authors.yml"  #作者信息
  # - tags:
  #     tags_file: tag.md  #分类标签


# 需要准备相关.js、.css文件，才能使用
# extra_javascript:
#   - javascripts/extra.js
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# extra_css:
#   - stylesheets/extra.css

#cookie追踪
#cookie
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/heart
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/heart-broken
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
  #     如果你同意,你可以帮助我们让我们的网站更好~
    #描述
